# Generated by Django 2.1.5 on 2019-04-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190415_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rh', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
